Repository Jihau/Harmonia, pull requests merged in 2023-02, with the labels that each got.

#41 fix for opening regirstration-view from the registrationLink.
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
Labels: bug

#50 DTO + mocking
  Backend/pom.xml
  Backend/src/main/java/com/harmonia/backend/controller/UserController.java
  Backend/src/main/java/com/harmonia/backend/po/UserResponse.java
  Backend/src/main/java/com/harmonia/backend/service/UserService.java
  Backend/src/test/java/com/harmonia/backend/serviceTests/UserServiceTest.java
  Frontend/pom.xml
  Frontend/src/main/java/com/harmonia/client/UserClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/po/UserPO.java
  Frontend/src/test/java/com/harmonia/client/UserClientTest.java
Labels: enhancement, check what has changed

#53 Sp3 mock2
  Backend/src/main/java/com/harmonia/backend/controller/UserController.java
  Backend/src/main/java/com/harmonia/backend/service/UserService.java
Labels: enhancement

#56 User settings page
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/client/UserClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/java/com/harmonia/po/ValidationPOJO.java
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
  Frontend/src/test/java/com/harmonia/client/EditUserClientTest.java
  Frontend/src/test/java/com/harmonia/client/UserClientTest.java
Labels: enhancement
