Repository Jihau/Harmonia, pull requests merged in 2023-04, with the labels that each got.

#154 Friends requests and tests
  Backend/src/main/java/com/harmonia/backend/controller/FriendController.java
  Backend/src/main/java/com/harmonia/backend/domain/Friend.java
  Backend/src/main/java/com/harmonia/backend/repository/FriendRepository.java
  Frontend/src/main/java/com/harmonia/client/FriendClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/po/FriendPo.java
  Frontend/src/test/java/com/harmonia/client/FriendClientTest.java
Labels: bug fix, enhancement, check what has changed

#157 Streaming update
  Backend/pom.xml
  Backend/src/main/java/com/harmonia/backend/config/APIKeyValidatorFilter.java
  Backend/src/main/java/com/harmonia/backend/config/WebSocketConfig.java
  Backend/src/main/java/com/harmonia/backend/mappers/StreamMessagesRequestMapper.java
  Backend/src/main/java/com/harmonia/backend/po/StreamMessageRequest.java
  Backend/src/main/java/com/harmonia/backend/streams/DirectMessageStream.java
  Backend/src/main/java/com/harmonia/backend/utils/HarmoniaUtils.java
  Backend/src/main/resources/application.properties
  Backend/src/main/resources/public/streams/index.html
  Backend/src/main/resources/public/stylesheet.css
Labels: bug fix, enhancement, check what has changed, Needs more work

#158 Localization
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/resources/properties/languageAR.properties
  Frontend/src/main/resources/properties/languageEN.properties
Labels: enhancement, Needs more work

#160 adding channels working
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/TextConstants.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/java/com/harmonia/view/AddChannelWindow.fxml
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
  Frontend/src/main/resources/properties/languageAR.properties
  Frontend/src/main/resources/properties/languageEN.properties
  Frontend/src/main/resources/properties/languageFI.properties
Labels: bug fix, enhancement, check what has changed

#162 Server creator
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/client/PublicMessageClient.java
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/client/ServerMemberClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaViewsConstants.java
  Frontend/src/main/java/com/harmonia/constants/TextConstants.java
  Frontend/src/main/java/com/harmonia/controller/CommunitiesController.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/controller/MainViewController.java
  Frontend/src/main/java/com/harmonia/controller/NavController.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/java/com/harmonia/controller/RegistrationController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/java/com/harmonia/po/NavPO.java
  Frontend/src/main/resources/com/harmonia/AddChannelWindow.fxml
  Frontend/src/main/resources/com/harmonia/NewServerWindow.fxml
  Frontend/src/main/resources/com/harmonia/css/navMenu.css
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/nav.fxml
  Frontend/src/main/resources/com/harmonia/navOld.fxml
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
  Frontend/src/main/resources/properties/languageAR.properties
  Frontend/src/main/resources/properties/languageEN.properties
  Frontend/src/main/resources/properties/languageFI.properties
  Frontend/src/test/java/com/harmonia/client/ServerMemberClientTest.java
Labels: bug fix, enhancement, check what has changed

#163 Adding contentful to login. Password field localization needs more work.
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/client/ContentfulClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaMessagesConstants.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
  Frontend/src/main/java/module-info.java
  Frontend/src/test/java/com/harmonia/client/ContentfulClientTest.java
Labels: bug fix, enhancement, check what has changed

#164 -Arabic lang localization
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/resources/com/harmonia/img/plusIcon.png
  Frontend/src/main/resources/com/harmonia/server-view.fxml
  Frontend/src/main/resources/properties/languageAR.properties
Labels: enhancement

#165 Fix for login localization
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/client/ContentfulClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
Labels: bug fix, enhancement

#167 Refresh the scene immediately after choosing the language.
  Frontend/src/main/java/com/harmonia/client/ContentfulClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/resources/com/harmonia/login-view.fxml
  Frontend/src/test/java/com/harmonia/client/ContentfulClientTest.java
Labels: bug fix, enhancement
