Repository Jihau/Harmonia, pull requests merged in 2023-05, with the labels that each got.

#168 -Adding new endpoint to get DMs based on a timestamp.
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/domain/DirectMessage.java
  Backend/src/main/java/com/harmonia/backend/po/DmessageResponse.java
  Backend/src/main/java/com/harmonia/backend/repository/DirectMessageRepository.java
  Backend/src/main/java/com/harmonia/backend/service/DirectMessageService.java
Labels: documentation, enhancement, check what has changed

#172 Fix for the styles in direct messages and choicebox in user settings
  Frontend/src/main/java/com/harmonia/controller/DirectMessagesController.java
  Frontend/src/main/java/com/harmonia/view/UsersListView.java
  Frontend/src/main/resources/com/harmonia/css/chat.css
  Frontend/src/main/resources/com/harmonia/css/form.css
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
Labels: bug fix

#173 Adding WebSockets to direct messages
  Backend/src/main/java/com/harmonia/backend/BackendApplication.java
  Backend/src/main/java/com/harmonia/backend/config/WebSocketConfig.java
  Backend/src/main/java/com/harmonia/backend/constants/HarmoniaConstants.java
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/streams/DirectMessageStream.java
  Backend/src/main/java/com/harmonia/backend/utils/HarmoniaUtils.java
  Backend/src/main/java/com/harmonia/backend/websockets/ChatController.java
  Backend/src/main/java/com/harmonia/backend/websockets/OutputMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/RefreshMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompClientSessionHandler.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompWebSocketClient.java
  Backend/src/main/resources/application.properties
  Backend/src/main/resources/public/streams/index.html
  Frontend/pom.xml
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/websockets/StompClientSessionHandler.java
  Frontend/src/main/java/com/harmonia/websockets/StompWebSocketClient.java
  Frontend/src/main/java/module-info.java
Labels: enhancement, check what has changed, Needs more work

#174 Constants
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
Labels: bug fix

#181 Comments
  Backend/src/main/java/com/harmonia/backend/config/APIKeyValidatorFilter.java
  Backend/src/main/java/com/harmonia/backend/config/UserConfig.java
  Backend/src/main/java/com/harmonia/backend/config/WebSocketConfig.java
  Backend/src/main/java/com/harmonia/backend/constants/HarmoniaConstants.java
  Backend/src/main/java/com/harmonia/backend/mappers/StreamMessagesRequestMapper.java
  Backend/src/main/java/com/harmonia/backend/po/StreamMessageRequest.java
  Backend/src/main/java/com/harmonia/backend/utils/HarmoniaUtils.java
  Backend/src/main/java/com/harmonia/backend/utils/KeyValidator.java
  Backend/src/main/java/com/harmonia/backend/websockets/ChatController.java
  Backend/src/main/java/com/harmonia/backend/websockets/OutputMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/RefreshMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompClientSessionHandler.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompWebSocketClient.java
Labels: documentation

#182 Comments
  Frontend/src/main/java/com/harmonia/po/DMessagePO.java
  Frontend/src/main/java/com/harmonia/po/NavPO.java
  Frontend/src/main/java/com/harmonia/websockets/StompClientSessionHandler.java
  Frontend/src/main/java/com/harmonia/websockets/StompWebSocketClient.java
Labels: documentation

#183 backend javadoc comments
  Backend/src/main/java/com/harmonia/backend/BackendApplication.java
  Backend/src/main/java/com/harmonia/backend/controller/FriendController.java
  Backend/src/main/java/com/harmonia/backend/domain/Friend.java
  Backend/src/main/java/com/harmonia/backend/mappers/FriendMapper.java
  Backend/src/main/java/com/harmonia/backend/po/FriendRequest.java
  Backend/src/main/java/com/harmonia/backend/service/DirectMessageService.java
  Backend/src/main/java/com/harmonia/backend/service/FriendService.java
  Backend/src/main/java/com/harmonia/backend/websockets/ChatController.java
  Backend/src/main/java/com/harmonia/backend/websockets/OutputMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/RefreshMessage.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompClientSessionHandler.java
  Backend/src/main/java/com/harmonia/backend/websockets/StompWebSocketClient.java
Labels: documentation

#184 frontend javadocs for a lot of stuff
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaMessagesConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaViewsConstants.java
  Frontend/src/main/java/com/harmonia/controller/DirectMessagesController.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/java/com/harmonia/controller/RegistrationController.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaTaskRefresher.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
Labels: documentation

#185 Fixing broken documentation..
  Backend/src/main/java/com/harmonia/backend/utils/HarmoniaUtils.java
  Backend/src/main/java/com/harmonia/backend/utils/KeyValidator.java
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/client/ContentfulClient.java
  Frontend/src/main/java/com/harmonia/client/FriendClient.java
  Frontend/src/main/java/com/harmonia/client/PublicMessageClient.java
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaMessagesConstants.java
  Frontend/src/main/java/com/harmonia/constants/TextConstants.java
  Frontend/src/main/java/com/harmonia/controller/CommunitiesController.java
  Frontend/src/main/java/com/harmonia/controller/DirectMessagesController.java
  Frontend/src/main/java/com/harmonia/controller/RegistrationController.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/java/com/harmonia/po/DMessagePO.java
  Frontend/src/main/java/com/harmonia/po/FriendPo.java
  Frontend/src/main/java/com/harmonia/po/NavPO.java
  Frontend/src/main/java/com/harmonia/po/ServerPO.java
  Frontend/src/main/java/com/harmonia/po/UserPO.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaDataLoader.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaTaskRefresher.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
  Frontend/src/main/java/com/harmonia/view/MessagesListView.java
  Frontend/src/main/java/com/harmonia/view/UsersListView.java
  Frontend/src/main/java/com/harmonia/websockets/StompClientSessionHandler.java
  Frontend/src/main/java/com/harmonia/websockets/StompWebSocketClient.java
Labels: bug fix, documentation
