Repository Jihau/Harmonia, pull requests merged in 2023-03, with the labels that each got.

#72 Creating ServerMember tables in domain and correcting file names
  Backend/src/main/java/com/harmonia/backend/domain/ServerMember.java
  Backend/src/main/java/com/harmonia/backend/domain/ServerMembers.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerMemberRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerMembersRepository.java
Labels: enhancement

#75 Chat view controller
  Frontend/src/main/java/com/harmonia/client/DirectMessageClient.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/po/MessagePO.java
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/test/java/com/harmonia/client/DMClientTest.java
Labels: bug fix, enhancement

#77 LoginButton moved to proper position.
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
Labels: enhancement

#78 Query searches for searching servers by ownerId and memberId
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
  Backend/src/main/java/com/harmonia/backend/controller/ServerMemberController.java
  Backend/src/main/java/com/harmonia/backend/domain/Server.java
  Backend/src/main/java/com/harmonia/backend/domain/ServerMember.java
  Backend/src/main/java/com/harmonia/backend/po/ServerResponse.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerMemberRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerRepository.java
  Backend/src/main/java/com/harmonia/backend/service/ServerMemberService.java
  Backend/src/main/java/com/harmonia/backend/service/ServerService.java
Labels: enhancement

#79 Query search for searching servers by category
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
  Backend/src/main/java/com/harmonia/backend/domain/Server.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerRepository.java
  Backend/src/main/java/com/harmonia/backend/service/ServerService.java
Labels: enhancement

#85 Listing servers on client (method + test) and adding some PO classes
  Backend/src/main/java/com/harmonia/backend/domain/Server.java
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/po/ChannelPO.java
  Frontend/src/main/java/com/harmonia/po/PublicMessagePO.java
  Frontend/src/main/java/com/harmonia/po/ServerMemberPO.java
  Frontend/src/main/java/com/harmonia/po/ServerPO.java
  Frontend/src/main/java/com/harmonia/po/UserPO.java
  Frontend/src/test/java/com/harmonia/client/ServerClientTest.java
Labels: enhancement

#86 Displaying servers (all atm) in serverListView
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
Labels: enhancement

#88 listing servers
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/client/ServerMemberClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/po/MessagePO.java
  Frontend/src/test/java/com/harmonia/client/DMClientTest.java
  Frontend/src/test/java/com/harmonia/client/ServerClientTest.java
  Frontend/src/test/java/com/harmonia/client/ServerMemberClientTest.java
Labels: enhancement

#90 Channels client testing
  Frontend/src/test/java/com/harmonia/client/ChannelClientTest.java
Labels: enhancement

#91 fixing ServerClientTest: listServersByNameTest()
  Frontend/src/test/java/com/harmonia/client/ServerClientTest.java
Labels: bug fix

#92 Server view work started
  Frontend/src/main/java/com/harmonia/client/DirectMessageClient.java
  Frontend/src/main/java/com/harmonia/client/PublicMessageClient.java
  Frontend/src/main/java/com/harmonia/client/ServerMemberClient.java
  Frontend/src/main/java/com/harmonia/client/UserClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
  Frontend/src/main/java/com/harmonia/controller/RegistrationController.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/java/com/harmonia/po/ValidationPOJO.java
  Frontend/src/main/resources/com/harmonia/css/form.css
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
  Frontend/src/test/java/com/harmonia/client/DMClientTest.java
  Frontend/src/test/java/com/harmonia/client/UserClientTest.java
Labels: bug fix, documentation, enhancement, check what has changed, question

#95 public messages test.
  Frontend/src/main/java/com/harmonia/po/PublicMessagePO.java
  Frontend/src/test/java/com/harmonia/client/PublicMessageClientTest.java
Labels: enhancement

#97 Documentation for backend classes pt.1
  Backend/src/main/java/com/harmonia/backend/config/UserConfig.java
  Backend/src/main/java/com/harmonia/backend/controller/ChannelController.java
  Backend/src/main/java/com/harmonia/backend/domain/User.java
  Backend/src/main/java/com/harmonia/backend/repository/ChannelRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/UserRepository.java
  Backend/src/main/java/com/harmonia/backend/service/UserService.java
Labels: documentation

#98 fixing mapping on servercontroller
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
Labels: bug fix

#99 PublicMessagesClient tests.
  Backend/src/main/java/com/harmonia/backend/controller/PublicMessageController.java
  Backend/src/main/java/com/harmonia/backend/domain/Server.java
  Backend/src/main/java/com/harmonia/backend/service/PublicMessageService.java
  Frontend/src/main/java/com/harmonia/client/PublicMessageClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/test/java/com/harmonia/client/ChannelClientTest.java
  Frontend/src/test/java/com/harmonia/client/PublicMessageClientTest.java
Labels: enhancement

#100 Ui fixes
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/resources/com/harmonia/css/form.css
  Frontend/src/main/resources/com/harmonia/css/listView.css
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/login-view.fxml
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
Labels: bug fix, enhancement, Needs more work

#102 Server list bug fix
  Backend/src/main/resources/application.properties
Labels: bug fix

#103 Some refactoring
  Backend/src/main/java/com/harmonia/backend/controller/ChannelController.java
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/controller/PublicMessageController.java
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
  Backend/src/main/java/com/harmonia/backend/controller/ServerMemberController.java
  Backend/src/main/java/com/harmonia/backend/controller/UserController.java
  Backend/src/main/java/com/harmonia/backend/po/CredentialsPO.java
Labels: documentation, enhancement

#105 Sp4 lombok and cloud
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/java/com/harmonia/po/ChannelPO.java
  Frontend/src/main/java/com/harmonia/po/MessagePO.java
  Frontend/src/main/java/com/harmonia/po/PublicMessagePO.java
  Frontend/src/main/java/com/harmonia/po/ServerMemberPO.java
  Frontend/src/main/java/com/harmonia/po/ServerPO.java
  Frontend/src/main/java/com/harmonia/po/UserPO.java
  Frontend/src/main/java/module-info.java
  Frontend/src/main/resources/com/harmonia/img/pen.png
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
Labels: bug fix, enhancement, check what has changed

#107 Server backend
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerRepository.java
  Backend/src/main/java/com/harmonia/backend/service/ServerService.java
Labels: enhancement

#108 fixed lombok breaking PO-classes
  Frontend/pom.xml
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/resources/com/harmonia/img/harmoniaIcon.png
Labels: bug fix, enhancement

#110 Change profile bio from profile
  Frontend/src/main/java/com/harmonia/client/UserClient.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/test/java/com/harmonia/client/EditUserClientTest.java
  Frontend/src/test/java/com/harmonia/client/PublicMessageClientTest.java
Labels: enhancement

#109 Server view2
  Frontend/src/main/java/com/harmonia/HarmoniaController.java
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/CommunitiesController.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/java/com/harmonia/po/ChannelPO.java
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
  Frontend/src/test/java/com/harmonia/client/PublicMessageClientTest.java
Labels: enhancement, Needs more work, question

#111 Constants fix
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
Labels: bug fix, check what has changed

#112 listing users in direct message view
  Frontend/src/main/java/com/harmonia/constants/HarmoniaData.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaDataLoader.java
  Frontend/src/main/java/com/harmonia/view/UsersListView.java
  Frontend/src/main/java/module-info.java
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
Labels: enhancement

#113 documentation for ChannelPO, HarmoniaApplication, HarmoniaConstants, UserClient
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/client/ChannelClient.java
  Frontend/src/main/java/com/harmonia/client/DirectMessageClient.java
  Frontend/src/main/java/com/harmonia/client/UserClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/po/ChannelPO.java
Labels: documentation

#114 Documentation
  Backend/src/main/java/com/harmonia/backend/controller/ChannelController.java
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/controller/PublicMessageController.java
  Backend/src/main/java/com/harmonia/backend/controller/ServerController.java
  Backend/src/main/java/com/harmonia/backend/controller/ServerMemberController.java
  Backend/src/main/java/com/harmonia/backend/controller/UserController.java
  Backend/src/main/java/com/harmonia/backend/domain/Channel.java
  Backend/src/main/java/com/harmonia/backend/domain/DirectMessage.java
  Backend/src/main/java/com/harmonia/backend/domain/PublicMessage.java
  Backend/src/main/java/com/harmonia/backend/domain/Server.java
  Backend/src/main/java/com/harmonia/backend/domain/ServerMember.java
  Backend/src/main/java/com/harmonia/backend/domain/User.java
  Backend/src/main/java/com/harmonia/backend/mappers/DirectMessagesMapper.java
  Backend/src/main/java/com/harmonia/backend/mappers/ServerMemberMapper.java
  Backend/src/main/java/com/harmonia/backend/mappers/UserMapper.java
  Backend/src/main/java/com/harmonia/backend/po/ChangePasswordRequest.java
  Backend/src/main/java/com/harmonia/backend/po/CreateUserRequest.java
  Backend/src/main/java/com/harmonia/backend/po/CredentialsPO.java
  Backend/src/main/java/com/harmonia/backend/po/DMessageRequest.java
  Backend/src/main/java/com/harmonia/backend/po/DmessageResponse.java
  Backend/src/main/java/com/harmonia/backend/po/ServerMemberRequest.java
  Backend/src/main/java/com/harmonia/backend/po/ServerResponse.java
  Backend/src/main/java/com/harmonia/backend/po/UserResponse.java
  Backend/src/main/java/com/harmonia/backend/repository/ChannelRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/DirectMessageRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/PublicMessageRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerMemberRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/ServerRepository.java
  Backend/src/main/java/com/harmonia/backend/repository/UserRepository.java
  Backend/src/main/java/com/harmonia/backend/service/ChannelService.java
  Backend/src/main/java/com/harmonia/backend/service/DirectMessageService.java
  Backend/src/main/java/com/harmonia/backend/service/PublicMessageService.java
  Backend/src/main/java/com/harmonia/backend/service/ServerMemberService.java
  Backend/src/main/java/com/harmonia/backend/service/ServerService.java
  Backend/src/main/java/com/harmonia/backend/service/UserService.java
Labels: documentation

#115 documentation for ChatController, CommunitiesController, HarmoniaData…
  Frontend/src/main/java/com/harmonia/client/PublicMessageClient.java
  Frontend/src/main/java/com/harmonia/client/ServerClient.java
  Frontend/src/main/java/com/harmonia/client/ServerMemberClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaData.java
  Frontend/src/main/java/com/harmonia/controller/ChatController.java
  Frontend/src/main/java/com/harmonia/controller/CommunitiesController.java
  Frontend/src/main/java/com/harmonia/controller/LoginController.java
Labels: documentation

#117 some style for server-view and adding stylesheet to mycommunities-view
  Frontend/src/main/resources/com/harmonia/css/listView.css
  Frontend/src/main/resources/com/harmonia/img/chatBubble.png
  Frontend/src/main/resources/com/harmonia/img/stones.png
  Frontend/src/main/resources/com/harmonia/img/stonesblue.png
  Frontend/src/main/resources/com/harmonia/img/userSmile.png
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
Labels: enhancement

#119 Style for list views
  Frontend/src/main/resources/com/harmonia/css/listView.css
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/server-view.fxml
Labels: enhancement

#120 Edit remove fix
  Frontend/src/main/java/com/harmonia/controller/CommunitiesController.java
  Frontend/src/main/java/com/harmonia/controller/DirectMessagesController.java
  Frontend/src/main/java/com/harmonia/controller/ServerController.java
Labels: bug fix, documentation, enhancement

#121 Refactoring
  Frontend/src/main/java/com/harmonia/controller/ProfileController.java
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
Labels: documentation, enhancement

#122 Fixing inconsintencies between ui scenes.
  Frontend/src/main/resources/com/harmonia/css/chat.css
  Frontend/src/main/resources/com/harmonia/harmonia-view.fxml
  Frontend/src/main/resources/com/harmonia/login-view.fxml
  Frontend/src/main/resources/com/harmonia/mycommunities-view.fxml
  Frontend/src/main/resources/com/harmonia/profile-view.fxml
  Frontend/src/main/resources/com/harmonia/registration-view.fxml
Labels: bug fix

#126 Refactoring
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
Labels: documentation, enhancement

#134 Documentation messagePO,PublicMessagePO and ServerMemberPO
  Frontend/src/main/java/com/harmonia/model/Message.java
  Frontend/src/main/java/com/harmonia/po/MessagePO.java
  Frontend/src/main/java/com/harmonia/po/PublicMessagePO.java
  Frontend/src/main/java/com/harmonia/po/ServerMemberPO.java
Labels: documentation

#135 Documentation
  Frontend/src/main/java/com/harmonia/utils/HarmoniaDataLoader.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
Labels: documentation

#138 Direct messages fix.
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/domain/DirectMessage.java
  Backend/src/main/java/com/harmonia/backend/repository/DirectMessageRepository.java
  Backend/src/main/java/com/harmonia/backend/service/DirectMessageService.java
  Backend/src/main/resources/application.properties
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/client/DirectMessageClient.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaData.java
  Frontend/src/main/java/com/harmonia/controller/DirectMessagesController.java
  Frontend/src/main/java/com/harmonia/po/DMessagePO.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaDataLoader.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaTaskRefresher.java
  Frontend/src/main/java/com/harmonia/view/MessagesListView.java
  Frontend/src/main/java/com/harmonia/view/UsersListView.java
  Frontend/src/main/resources/com/harmonia/messages-view.fxml
Labels: bug fix, documentation, enhancement, check what has changed

#142 fixed edit public message test
  Frontend/src/test/java/com/harmonia/client/PublicMessageClientTest.java
Labels: bug fix

#143 Updating AWS url
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
Labels: bug fix

#144 Update README.md
  README.md
Labels: bug fix

#146 new backend URL
  Backend/src/main/resources/application.properties
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
Labels: enhancement

#147 Refactoring
  Backend/src/main/java/com/harmonia/backend/controller/DirectMessageController.java
  Backend/src/main/java/com/harmonia/backend/controller/PublicMessageController.java
  Backend/src/main/java/com/harmonia/backend/po/PmessageResponse.java
  Backend/src/main/java/com/harmonia/backend/service/DirectMessageService.java
  Backend/src/main/java/com/harmonia/backend/service/PublicMessageService.java
  Backend/src/main/resources/application.properties
Labels: enhancement

#149 success label drawn appropriately
  Frontend/src/main/java/com/harmonia/controller/SettingsController.java
  Frontend/src/main/resources/com/harmonia/usersettings-view.fxml
Labels: bug fix

#150 Friends
  Backend/src/main/java/com/harmonia/backend/domain/Friend.java
Labels: enhancement

#151 Adding API key to endpoints
  Backend/src/main/java/com/harmonia/backend/config/APIKeyValidatorFilter.java
  Backend/src/main/java/com/harmonia/backend/constants/HarmoniaConstants.java
  Backend/src/main/java/com/harmonia/backend/utils/KeyValidator.java
  Backend/src/main/resources/application.properties
  Backend/src/test/java/com/harmonia/backend/utils/KeyValidatorTest.java
  Frontend/pom.xml
  Frontend/src/main/java/com/harmonia/HarmoniaApplication.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaConstants.java
  Frontend/src/main/java/com/harmonia/constants/HarmoniaData.java
  Frontend/src/main/java/com/harmonia/utils/HarmoniaUtils.java
  Frontend/src/main/java/module-info.java
Labels: enhancement, check what has changed
